name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Verify workspace
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Package.json content:"
          cat package.json
          echo "Vite config content:"
          cat vite.config.js

      - name: Install dependencies
        run: |
          npm install
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Installed packages:"
          npm list --depth=0

      - name: Build
        run: |
          echo "Running build..."
          echo "Listing src directory:"
          ls -la src/
          echo "Content of package.json:"
          cat package.json
          echo "Content of vite.config.js:"
          cat vite.config.js
          echo "-------- RUNNING BUILD --------"
          npm run build || true
          echo "-------- BUILD FINISHED --------"
          echo "Checking if dist exists:"
          ls -la || true
          if [ -d "dist" ]; then
            echo "Dist directory exists, listing contents:"
            ls -la dist/ || true
          else
            echo "Dist directory does not exist!"
            echo "Checking current directory structure:"
            pwd
            find . -type d -maxdepth 2 || true
          fi

      - name: Verify dist contents
        if: always()
        run: |
          echo "Checking all directories:"
          ls -la
          if [ -d "dist" ]; then
            echo "Dist directory exists, checking contents:"
            find dist -type f | sort
            if [ ! -f "dist/index.html" ]; then
              echo "Error: index.html not found in dist folder"
              exit 1
            else
              echo "Success: index.html found in dist folder"
            fi
          else
            echo "Error: dist directory does not exist!"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create test HTML
        run: |
          echo "Creating test HTML file"
          mkdir -p test-dist
          cat > test-dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Work Tracker Pro - Test Page</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
          </head>
          <body>
            <h1>Work Tracker Pro</h1>
            <p>Esta es una página de prueba para GitHub Pages</p>
            <p>Si puedes ver esta página, el despliegue básico funciona.</p>
          </body>
          </html>
          EOL
          echo "Test HTML created:"
          cat test-dist/index.html

      - name: Upload test artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "test-dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
