name: Deploy Static Test Page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test page only
        run: |
          echo "Creating test HTML file"
          mkdir -p test-dist
          cat > test-dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Work Tracker Pro - Test Page</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; line-height: 1.6; }
              .container { max-width: 800px; margin: 0 auto; background: #f9f9f9; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
              h1 { color: #0066cc; }
              .success { color: green; font-weight: bold; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Work Tracker Pro</h1>
              <p>Esta es una página de prueba para GitHub Pages</p>
              <p class="success">✅ Si puedes ver esta página, el despliegue básico funciona correctamente.</p>
              <p>Una vez que esta página funcione, podremos implementar la aplicación completa.</p>
            </div>
          </body>
          </html>
          EOL
          echo "Test HTML created successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload test page
        uses: actions/upload-pages-artifact@v3
        with:
          path: "test-dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
